# yamllint disable-file
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "datetimepicker"
  description: "jQuery plugin select date and time"
  title: "DateTimePicker"
  tags:
    - emr
spec:
  type: "library"
  owner: "group:default/emr-tasy-framework-contributors"
  lifecycle: "production"